### ISSUE TITLE
Is this mod necessary?

### ISSUE THREAD

**Issue by svm420** [jrodrigv/PhysicsRangeExtender#1]
Hey not sure if you are aware, but since 1.2(?) you can set the physic ranges with MM. They are in the Physics.cfg file in the main game folder and you can target them with MM like this. Just wanted to let you know in case you didn't. Really appreciate all your doing for BDArmory. :) 

@PHYSICSGLOBALS
{
	@VesselRanges
	{
		@flying
		{
			// load = 2250
			// unpack = 2000
			// unload = 22500
			// pack = 25000
			@pack = newValue
			@unload = newValue
			@load = newValue
			 @unpack = newValue
		}
	}
	
}

**Comment by jrodrigv** [comment]
Thanks! I didn't know :) I will give a try to see if it works fine .

**Comment by jrodrigv** [comment]
So after testing this approach I think it is not working as expected.

I have used this MM script, that is equivalent to what the mod is basically doing. But it seems that when a new vessel is created (like when a missile is fired) then the new vessel is not using the new ranges at all.

Maybe I'm doing something wrong, but I have double checked the log and KSP is loading the script and updating the database.

@PHYSICSGLOBALS
{
@VesselRanges
{
@flying
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@escaping
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@landed
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@orbit
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@prelaunch
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@splashed
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
@subOrbital
{
@pack = 200000
@unload = 190000
@load = 181000
@unpack = 172900
}
}

}

**Comment by svm420** [comment]
I am at a loss then I have been using with a 50km range when flying and it seems to perform as expected. I would suggest hitting the official forum with the issue as it maybe something squad can check/fix during the prerelease. If not the mod may very well be necessary.

**Comment by jrodrigv** [comment]
I will do thanks!

**Comment by MuricanJeb** [comment]
Some people don't know how to make patches like these, so I think we should keep the mod.
