### ISSUE TITLE
All sounds ignore the distances to their sources

### ISSUE THREAD

**Issue by ScorpionSK** [jrodrigv/PhysicsRangeExtender#13]
All sounds from all vessels are heared at the same place and at the same time disregarding of the distance to the vessel. KSP version 1.7.3. PRE version 1.15.0.

**Comment by jrodrigv** [comment]
I have seen this too. I don't have a fix for it, because it is likely too be something due to KSP it self.

**Comment by jrodrigv** [comment]
I can confirm this is a KSP issue, I have opened an issue on the KSP bug tracker

**Comment by jrodrigv** [comment]
This issue has been fixed in KSP 1.9 (with latest release of PRE v1.18)
