### ISSUE TITLE
Freeze on MOD activation

### ISSUE THREAD

**Issue by CrickCrickBang** [jrodrigv/PhysicsRangeExtender#15]
KSP v1.8.1
PRE v1.17

If the MOD is activated in the settings config, the game freezes on launch of any craft. If the MOD is activated during flight, the game also freezes.

[output_log.txt](https://github.com/jrodrigv/PhysicsRangeExtender/files/3861444/output_log.txt)

[output_log.txt](https://github.com/jrodrigv/PhysicsRangeExtender/files/3861449/output_log.txt)

**Comment by jrodrigv** [comment]
I need the KSP.log

**Comment by CrickCrickBang** [comment]
I can't find that at all, only output.logs

**Comment by jrodrigv** [comment]
The KSP.log file is always generated as soon as you execute KSP.exe inside
the very same folder

**Comment by CrickCrickBang** [comment]
My bad,

[KSP.log](https://github.com/jrodrigv/PhysicsRangeExtender/files/3864573/KSP.log)

**Comment by jrodrigv** [comment]
Sorry but I can't see anything strange on that log. Can you play the game until it freezes and then send me back the KSP.log file?

**Comment by CrickCrickBang** [comment]
Absoloutely

**Comment by CrickCrickBang** [comment]
[KSP.log](https://github.com/jrodrigv/PhysicsRangeExtender/files/3864832/KSP.log)

**Comment by CrickCrickBang** [comment]
After reviewing that myself a little bit I decided to find out why GU (Galaxies Unbound) was having such a substantial effect when it isn't installed. Found a Kopernicus file hiding in the Logs, perhaps that was the issue

**Comment by jrodrigv** [comment]
Is this a new game or a game you had saved in a previous version of KSP? 
Can you reproduce it using a very simple vessel buildt with KSP 1.8.1?
Which range do you have set in PRE?

**Comment by CrickCrickBang** [comment]
It is a save from 1.7.3 now that you mention it. PRE would be set to
default settings as I've uninstalled and reinstalled everything, including
KSP itself. I'll make a new save, and I'll make a simple craft as you
mention, and I'll get back to you

**Comment by CrickCrickBang** [comment]
No dice...

[KSP.log](https://github.com/jrodrigv/PhysicsRangeExtender/files/3865070/KSP.log)

**Comment by jrodrigv** [comment]
uhmm can you try to increase the terrain graphics settings? and send me a screenshot of your graphic settings

**Comment by CrickCrickBang** [comment]
Give me a moment, I'll do both, but after looking in my settings config I found that GU had added presets, so I've removed those entirely and will give it yet another shot. Thanks for your patience thus far.

**Comment by CrickCrickBang** [comment]
You can close this one. Thank you, kind sir, for all your insight. Turns out I just need to make sure I go through all my files after an update and after removing large mods.

**Comment by jrodrigv** [comment]
I'm glad we found the problem :)
