### ISSUE TITLE
Breaking Ground deployable science equipment is destroyed when loaded.

### ISSUE THREAD

**Issue by Kev1n8088** [jrodrigv/PhysicsRangeExtender#16]
When a breaking ground deployable science station is loaded by this, it is destroyed.

**Comment by jrodrigv** [comment]
Which KSP and PRE version are you using? Would you mind attaching the KSP.log file to check when this happens?

**Comment by Kev1n8088** [comment]
I am uncertain which PRE version I am using, but at the time of writing, I believe it is the newest version. I am using KSP 1.9.1. I have a number of mods installed, but there are no physics or terrain mods. (I'm not sure if EVE is a terrain mod, seems to be just a visual mod.)

I don't have the logs as it happened yesterday and I think it was deleted by KSP. This is what happened: I was performing a rendezvous above the mun after a Munar landing and was overflying the science equipment that I had deployed previously. I was about 13KM in altitude. PRE switched to the deployed science and was lifting them. I was performing a burn at the time so I switched back to my vessel in orbit. PRE repetitively switched to the ground science to lift them, and I think they exploded when they hit the ground after being lifted. 

If you could change PRE so that it didn't affect deployed science, that would be great! Flags aren't affected, so I'm pretty sure this could be done. Currently, they are treated by PRE like ground vehicles, but they have insanely low crash tolerance, so when PRE lifts them, they crash and explode.

**Comment by jrodrigv** [comment]
Would you mind to test the latest release to see if it still happens?
