### ISSUE TITLE
Splashed vessels using GlobalRange?

### ISSUE THREAD

**Issue by TheDestroyer111** [jrodrigv/PhysicsRangeExtender#4]
As in title.
While AFAIK splashed vessels are not typically wrecked (although they could if they are sinking at that moment) by terrain getting unloaded, I often want to have an ability to switch between airborne/spaceborne things at longer distances without loading landed/splashed vessels at longer distance.
Although this would stop being a problem if the range became adjustable in-game :))))))

**Comment by jrodrigv** [comment]
Now it is :)
