### ISSUE TITLE
Enhanced Physics Range not working 

### ISSUE THREAD

**Issue by Battle8111** [jrodrigv/PhysicsRangeExtender#5]
I noticed that BDArmory continued supported extended physics range with the default setting being @ 200000 KM in the settings file, I tried to test this in-game with just the mod itself and was unable to load vehicles at this distance what so ever, not even at 20 KM. I noticed its at the default of 2.5 KM. I tested the issue both on 32 bit & 64 bit KSP . Game version is 1.3 and is latest version of BDArmory continued. 

I have no other mods that could conflict with this and have started a fresh in-game save file to eliminate any mod/or save file issues, I am gonna provide some screen shots to show that its not working for me. I am also running the game in 64 bit. Hopefully this is a bug and I am not providing information to an issue that is non-existent, maybe I am doing it wrong. 

Attachments below with pictures. **Will be willing to provide any more info if asked.** 
![20170704184854_1](https://user-images.githubusercontent.com/29904151/27844699-b156b75c-60ea-11e7-90a4-41aa8cc3d497.jpg)
![20170704184904_1](https://user-images.githubusercontent.com/29904151/27844700-b1572ea8-60ea-11e7-8532-1fea1d7d8c95.jpg)
![20170704184910_1](https://user-images.githubusercontent.com/29904151/27844702-b157ee74-60ea-11e7-9ec7-0c8ff0708bdd.jpg)
![20170704184920_1](https://user-images.githubusercontent.com/29904151/27844701-b1579f1e-60ea-11e7-92a7-95310cfa6d93.jpg)
![20170704184925_1](https://user-images.githubusercontent.com/29904151/27844703-b157fd56-60ea-11e7-800e-1342d9cc0d33.jpg)

**Comment by Battle8111** [comment]
I think I know why its not working; its currently not updated for KSP 1.3, I feel like a dunce, I wish I found this section earlier. Sorry to waste your time, this post can be deleted...

**Comment by jrodrigv** [comment]
Hi! Just to clarify. Do you mean that you are not using KSP 1.3 right? 

If you go to the releases section on this page you will the KSP 1.3 release

**Comment by Battle8111** [comment]
I am using KSP 1.3, sorry for the long delay, got busy with stuff. Unless somehow I am not using KSP 1.3 by accident. I will check the releases page and test out that version and get back to you.

**Comment by Battle8111** [comment]
I am testing the mod with Airpark, Vessel Mover and BDarmory continued and after around 15KM the opposing vehicle deletes itself.  I guess I can't seem to get this to work for me properly. :/

**Comment by jrodrigv** [comment]
The vessel that becomes debris, Is a landed vessel?

**Comment by Battle8111** [comment]
Yes, it does become debris the one landed, sorry for the long response again.

**Comment by jrodrigv** [comment]
You need to place landed vessels on static objects like Runways. Or using Kerbal Konstructs for example.

**Comment by Battle8111** [comment]
That makes sense! Thanks!
