### ISSUE TITLE
Problems for vessels entering Global Range distance of a cotroled vessel (landed or accelerating to orbit)

### ISSUE THREAD

**Issue by firehands974** [jrodrigv/PhysicsRangeExtender#6]
Controling a vessel for launch at KSC launchpad.
When an orbiting vessel (say at 75km altitude) entering the Global Range distance, I encontered two reactions :
- if the controled vessel have been launched. The orbiting vessel get the velocity vector of the accelerating vessel. Which result to a catastrophic reentry as it's not yet orbital velocity.
- if the controled vessel is still on lauchpad, The orbiting vessel have strange reaction. It's periapsis/appopsis start oscilating. And taking it's control, all the parts are moving around, like vibrating.

Here's a video showing these two cases : https://youtu.be/bhqmtm1n47E

The savegame I used is attached.
[PhysicsExtenderTest.zip](https://github.com/jrodrigv/PhysicsRangeExtender/files/1125997/PhysicsExtenderTest.zip)

**Comment by jrodrigv** [comment]
Hi, 
Thanks for your feedback. I think there is no much I can do to fix it.  If you read the OP of the mod thread I stated that most of these strange behaviours are a consequence of extending the physics range.

However, I might do some tweaks and give you some binaries to test it.

**Comment by firehands974** [comment]
Hi,

Sorry, I didn't see theses infos. And Yes I think, most of the problem is in KSP and not in your mod.

Meantime, I tried differents values for VesselRanges.Situation() using Module Manager and it seems that reversing the "pack" and "unload" parameters AND incressing the differecence between "load" and "unpack" reduce the occurence of sudden deorbit.

I think, it's because the vessel should be packed before unloaded.
And unpack can't be done in the same tic of the game. So increasing distance give the time to refresh between load and unpack. 

I tried with this values for 1000km distances wich seems good :
load : 99985
pack : 99990
unload : 100000
unpack : 99935

Increasing the load/unpack difference should be considered in case of high velocity returning from other planet vessel as the distance traveled between tics will be greater.

**Comment by spartankh** [comment]
So I'm having the first issue where my space station will deorbit as I try to rendezvous. As you've stated this is more of a problem with KSP and not the mod but is there something I can do to try and fix this? This mod is on CKAN so I imagine it's a fairly common mod but I really don't see many people running into this problem.

**Comment by jrodrigv** [comment]
@spartankh  I want to investigate this problem to see what can be done from code to minimize the problem.

I think at this moment the best you can try is to reduce the global range to something stockish (e.g 30 km ). 
If the issue still happening then we can say that the issue is due to the mod and not a KSP limitation.

Just to let you know, I'm commited to improve the physics extended range experience as much as I can.

**Comment by jrodrigv** [comment]
Hi @firehands974  and @spartankh .

I think I have fixed both issues. Would you mind to test this version?


[PhysicsRangeExtender.zip](https://github.com/jrodrigv/PhysicsRangeExtender/files/1290509/PhysicsRangeExtender.zip)

**Comment by jrodrigv** [comment]
Fixed
