### ISSUE TITLE
Re-enable Deactivation Option

### ISSUE THREAD

**Issue by DennisKerman** [jrodrigv/PhysicsRangeExtender#8]
Please, i really miss that Option. 
I used it all the time for normal ksp stuff... I'd rather keep the mod inactive until i want to use it instead of changing the p-range (no, not pee-range ;-)).
Furthermore it would have been nice if that setting (off or on) would be saved as the default then...

Even if its too much work to make that change, thanks alot for that awesome mod! I love it

**Comment by jrodrigv** [comment]
This has been  implemented again :)
